### ISSUE TITLE
Multithreading on arduino, i mean kinda multithreading

### ISSUE THREAD

**Issue by incebellipipo** [yazgit-labs/ferihabot#10]
You included the Scheduler library to ino file. This library allows you to create discrete loops. Create a new loop for the sensor readings. The motive behind this, ultrasonic sensors works with simple principle, sends a signal and waits for another to come back. This wait time can make system unresponsive sometimes. Imagine there is no obstacle and we wait to infinity. That's why we need the calculate sensor readings from another loop.

**Comment by rootofarch** [comment]
done in arduino-code branch
