### ISSUE TITLE
Adding sensor pin interfaces to pcb board

### ISSUE THREAD

**Issue by incebellipipo** [yazgit-labs/ferihabot#4]
- You need to add at least three Sensor pins
- This sensor pins could be either digital or analog sensors.
- Sensor pins _should be_ added as 3 pin array. 
  > `Groud - Voltage - Sensor`
  > _Also open to debate_
- **Be careful to satisfy main board's I/O voltage**

**Comment by bhctsntrk** [comment]
Completed
