### ISSUE TITLE
Fix-Add custom arduino libraries to firmware directory,

### ISSUE THREAD

**Issue by incebellipipo** [yazgit-labs/ferihabot#8]
- Arduino need a sketch file in a directory named after it. `/firmware/firmware.ino` like so.
- You also need to add custom library files to firmware directory, code won't work without them.
  - So you need to change directory as follow:
    `/ferihabot/firmware/libraries/`
  - The library files that i'm talking about is: QuadratureEncoder.h, Odometer.h,
- You also need to create a bash script that gets ready the all the library that sketch needs but it will be a different issue.

**Comment by rootofarch** [comment]
libraries are added to "**arduino-code**" branch and a _pull request created_
